---
- include: "install_packages.yml"
- include: "install_direnv.yml"

- name: "Install gems"
  gem: "name={{ item.name }} version={{ item.version }} state=present"
  become: no
  register: result
  until: "not result|failed"
  retries: 2
  environment: "{{ ruby_environment }}"
  with_items: "{{ tools }}"
  when: item.gem is defined

- include: "install_from_url.yml tool={{ item }}"
  with_items: "{{ tools }}"
  when: item.url is defined

