FROM ubuntu:14.04

# Install Ansible
RUN apt-get update
RUN apt-get install python-pip python-dev -y
RUN pip install ansible

RUN ansible-galaxy install shrikeh.curl
RUN ansible-galaxy install rvm_io.rvm1-ruby
RUN ansible-galaxy install azavea.golang

# Install Ansible inventory file
RUN echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts