FROM ubuntu:14.04

# Install Ansible
RUN apt-get update
RUN apt-get install software-properties-common -y
RUN apt-add-repository ppa:ansible/ansible -y
RUN apt-get update
RUN apt-get install ansible -y

RUN ansible-galaxy install shrikeh.curl
RUN ansible-galaxy install rvm_io.ruby
RUN ansible-galaxy install azavea.golang

# Install Ansible inventory file
RUN echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts
